/*
출력: AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
조건:
 - 2022년 1월 판매 기준
정렬: AUTHOR_ID, CATEGORY DESC
*/
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
JOIN
    AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN
    BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE
    DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_ID,
    B.CATEGORY
ORDER BY
    A.AUTHOR_ID,
    B.CATEGORY DESC;