/*
print: MONTH, COUNTRY, TRANS_COUNT, APPROVED_COUNT, TRANS_TOTAL_AMOUNT, APPROVED_TOTAL_AMOUNT
conditions:
 - for each month and each country
*/
SELECT
    DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH,
    COUNTRY,
    COUNT(*) AS TRANS_COUNT,
    COUNT(CASE
        WHEN STATE = 'approved' THEN STATE
    END) AS APPROVED_COUNT,
    SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
    SUM(CASE
        WHEN STATE = 'approved' THEN AMOUNT
        ELSE 0
    END) AS APPROVED_TOTAL_AMOUNT
FROM
    TRANSACTIONS
GROUP BY
    DATE_FORMAT(TRANS_DATE, '%Y-%m'),
    COUNTRY;