/*
print: START_DATE, END_DATE
order: took days to complete , START_DATE
*/
WITH TASK_NUMBER AS (
    SELECT
        START_DATE,
        END_DATE,
        ROW_NUMBER() OVER(ORDER BY START_DATE) AS RN
    FROM
        PROJECTS
),
PJ_GROUP AS (
    SELECT
        START_DATE,
        END_DATE,
        DATE_SUB(START_DATE, INTERVAL RN DAY) AS PROJECT
    FROM TASK_NUMBER
),
RESULT AS (
    SELECT
        MIN(START_DATE) AS PROJECT_START_DATE,
        MAX(END_DATE) AS PROJECT_END_DATE,
        DATEDIFF(MAX(END_DATE), MIN(START_DATE)) + 1 AS TOOK_DAYS
    FROM
        PJ_GROUP
    GROUP BY
        PROJECT
)
SELECT
    PROJECT_START_DATE,
    PROJECT_END_DATE
FROM
    RESULT
ORDER BY
    TOOK_DAYS,
    PROJECT_START_DATE;