/*
상품코드, 매출액 출력
정렬: 매출액 내림, 상품코드 오름
*/

SELECT
    PRODUCT_CODE,
    SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM
    PRODUCT P
INNER JOIN
    OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SUM(P.PRICE * O.SALES_AMOUNT) DESC,
    PRODUCT_CODE ASC;