/*
print: PRODUCT_ID, PRODUCT_NAME,
condition:
 - product sold in the first quarter of 2019
*/
WITH FIRST_QUARTER_SOLD AS (
    SELECT
        DISTINCT P.PRODUCT_ID
    FROM
        PRODUCT AS P
    JOIN
        SALES AS S ON P.PRODUCT_ID = S.PRODUCT_ID
    WHERE
        S.SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31'
),
EXCEPT_SOLD AS (
    SELECT
        DISTINCT P.PRODUCT_ID
    FROM
        PRODUCT AS P
    JOIN
        SALES AS S ON P.PRODUCT_ID = S.PRODUCT_ID
    WHERE
        NOT S.SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31'
),
ONLY_FIRST_QUARTER AS (
    SELECT
        PRODUCT_ID
    FROM
        FIRST_QUARTER_SOLD
    WHERE
        PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM EXCEPT_SOLD)
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME
FROM
    PRODUCT AS P
JOIN
    ONLY_FIRST_QUARTER AS O ON P.PRODUCT_ID = O.PRODUCT_ID;