/*
출력: ANIMAL_ID, ANIMAL_TYPE, NAME
조건:
 - 보호소에 들어올 당시 중성화 X
 - 보호소 나갈 당시 중성화 O
정렬: ANIMAL_ID
*/
SELECT
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    I.NAME
FROM
    ANIMAL_INS AS I
JOIN
    ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE
    I.SEX_UPON_INTAKE REGEXP 'Intact'
    AND (O.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered')
ORDER BY
    I.ANIMAL_ID;