/*
출력: REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
조건:
 - 서울에 위치한 식당
 - 리뷰 평균 점수는 소수점 세 번째 자리에서 반올림
정렬: SCORE DESC, FAVORITES DESC
*/
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO AS I
JOIN
    REST_REVIEW AS R ON I.REST_ID = R.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
GROUP BY
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS
ORDER BY
    SCORE DESC,
    FAVORITES DESC;