/*
print: YEAR, MONTH, PURCHASED_USERS, PURCHASED_RATIO
conditions:
 - 2021년 가입 회원 대상
 - 상품 구매 회원 수
 - 상품 구매 회원 비율
 - 소수 첫짜리까지 반올림
order
 - YEAR, MONTH
*/
WITH JOINED_2021 AS (
    SELECT
        COUNT(DISTINCT USER_ID) AS JOINED_2021_CNT
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
)

SELECT
    YEAR(O.SALES_DATE),
    MONTH(O.SALES_DATE),
    COUNT(DISTINCT O.USER_ID) AS PURCHASE_USERS,
    ROUND(
        COUNT(DISTINCT O.USER_ID) / (SELECT JOINED_2021_CNT FROM JOINED_2021)
    , 1) AS PURCHASE_RATIO
FROM
    USER_INFO AS I
JOIN
    ONLINE_SALE AS O ON I.USER_ID = O.USER_ID
WHERE
    YEAR(I.JOINED) = 2021
GROUP BY
    YEAR(O.SALES_DATE),
    MONTH(O.SALES_DATE)
ORDER BY
    YEAR(O.SALES_DATE),
    MONTH(O.SALES_DATE)

