/*
출력: 분기, 분화된 대장균 개체 총 수
조건: 분기에 'Q' 붙이기
정렬: 분기 오름
*/

SELECT 
    CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM 
    ECOLI_DATA
GROUP BY 
    CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q')
ORDER BY 
    CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q');
