/*
print: id
condition:
 - higher temparature compared to its previous dates(yesterday)
*/

/*
-- SOL1 --
SELECT
    W1.ID
FROM
    WEATHER W1
JOIN
    WEATHER W2 ON DATEDIFF(W1.RECORDDATE, W2.RECORDDATE) = 1
WHERE
    W1.TEMPERATURE > W2.TEMPERATURE;
*/

/*
-- SOL2 --
WITH PREVIOUS_WEATHER AS
(
    SELECT
        ID,
        RECORDDATE,
        TEMPERATURE,
        LAG(TEMPERATURE, 1) OVER (ORDER BY RECORDDATE) AS PREVIOUS_TEMPERATURE,
        LAG(RECORDDATE, 1) OVER (ORDER BY RECORDDATE) AS PREVIOUS_RECORDDATE
    FROM
        WEATHER
)
SELECT
    ID
FROM
    PREVIOUS_WEATHER
WHERE
    TEMPERATURE > PREVIOUS_TEMPERATURE
    AND RECORDDATE = DATE_ADD(PREVIOUS_RECORDDATE, INTERVAL 1 DAY);
*/

-- SOL3 --
SELECT
    W1.ID
FROM
    WEATHER W1
WHERE
    W1.TEMPERATURE > (
        SELECT
            W2.TEMPERATURE
        FROM
            WEATHER W2
        WHERE
            W2.RECORDDATE = DATE_SUB(W1.RECORDDATE, INTERVAL 1 DAY)
    );