/*
출력: MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
조건:
 - 리뷰를 가장 많이 작성한 회원의 리뷰 조회
정렬: REVIEW_DATE, REVIEW_TEXT
*/
-- 리뷰 가장 많이 작성한 회원의 ID 구하기
WITH MAX_REVIEW_MEMBER_ID AS (
    SELECT
        MEMBER_ID
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    ORDER BY
        COUNT(*) DESC
    LIMIT 1
)
SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM
    MEMBER_PROFILE AS M
JOIN
    REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
WHERE
    M.MEMBER_ID = (SELECT MEMBER_ID FROM MAX_REVIEW_MEMBER_ID)
ORDER BY
    R.REVIEW_DATE,
    R.REVIEW_TEXT;