/*
출력: MONTH, CAR_ID, RECORDS
조건:
 - 대여 시작일 기준 2022년 8월부터 10월까지 총 5번 이상 대여
 - 특정 월의 RECORDS가 0인 경우 출력 제외
정렬: MONTH, CAR_ID DESC
*/
WITH TRG_CAR AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
)
SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    AND CAR_ID IN (SELECT CAR_ID FROM TRG_CAR)
GROUP BY
    MONTH(START_DATE),
    CAR_ID
ORDER BY
    MONTH(START_DATE),
    CAR_ID DESC;
