/*
PRINT: ID, TYPE
*/
SELECT
    ID,
    CASE
        WHEN P_ID IS NULL THEN 'Root'
        WHEN ID NOT IN (SELECT P_ID FROM TREE WHERE P_ID IS NOT NULL) THEN 'Leaf'
        ELSE 'Inner'
    END AS TYPE
FROM
    TREE;