/*
아이스크림 성분 타입, 총주문량
정렬: 총주문량 ASC
*/

SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF F
INNER JOIN
    ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    SUM(TOTAL_ORDER) ASC;