/*
print: ID, VISIT_DATE, PEOPLE
condition:
 - three or more rows with consecutive id
 - and people is greater than or equal to 100 
*/

WITH LAG_LEAD_DATA AS (
    SELECT
        ID,
        VISIT_DATE,
        PEOPLE,
        LAG(PEOPLE, 1) OVER(ORDER BY ID)AS LAG_1_PEOPLE,
        LAG(PEOPLE, 2) OVER(ORDER BY ID) AS LAG_2_PEOPLE,
        LEAD(PEOPLE, 1) OVER(ORDER BY ID) AS LEAD_1_PEOPLE,
        LEAD(PEOPLE, 2) OVER(ORDER BY ID) AS LEAD_2_PEOPLE
    FROM
        STADIUM
)
SELECT
    ID,
    VISIT_DATE,
    PEOPLE
FROM
    LAG_LEAD_DATA
WHERE
    (PEOPLE >= 100 AND LAG_1_PEOPLE >= 100 AND LAG_2_PEOPLE >= 100)
    OR (PEOPLE >= 100 AND LAG_1_PEOPLE >= 100 AND LEAD_1_PEOPLE >= 100)
    OR (PEOPLE >= 100 AND LEAD_1_PEOPLE >= 100 AND LEAD_2_PEOPLE >= 100);