/*
가격대, 상품 개수
조건: 만원 단위
정렬: 가격대 asc
*/

SELECT
    CASE WHEN PRICE DIV 10000 = 0 THEN 0
         ELSE CONCAT(PRICE DIV 10000, '0000')
    END AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM
    PRODUCT
GROUP BY
    PRICE DIV 10000
ORDER BY
    PRICE DIV 10000 ASC;